<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>routes</string>
	</array>
	<key>name</key>
	<string>Routes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?x) \#[\D\d]*</string>
			<key>name</key>
			<string>comment.line.number-sign.routes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x) / [^#\s]*</string>
			<key>name</key>
			<string>string.unquoted.path.routes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>punctuation.definition.arrow.routes</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.routes</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.routes</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) ([\w\-:]+)? \. (\w+)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.name.routes</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) \( ([^)]+) \)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ANY|GET|POST|PUT|PATCH|DELETE</string>
			<key>name</key>
			<string>keyword.operator.routes</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.routes</string>
	<key>uuid</key>
	<string>c4dd1479-1f56-48db-bca2-9cdf09075536</string>
</dict>
</plist>
